# Name of lambda service
service: secret-santa

# Specifying specific version
# frameworkVersion: "=X.X.X"

# Runtime information
provider:
  name: aws
  runtime: python3.8
  region: eu-west-2
  stage: dev
  # IAM Policies
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - Fn::GetAtt: [secretSantaRecords, Arn]

# Additional plugins
plugins:
  - serverless-domain-manager
  - serverless-python-requirements

# Custom settings
custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: santaapi.alexhomingwong.co.uk
    staging: staging-santaapi.alexhomingwong.co.uk
    dev: dev-santaapi.alexhomingwong.co.uk
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    createRoute53Record: true
  # Not sure if below is needed for packaging python modules
  # pythonRequirements:
  #   dockerizePip: non-linux

# What files to include or exclude
package:
  exclude:
    - src/tests/*
    - keys.env

# Define lambda functions below
functions:
  randomiser: # Lambda name
    package: {} # This is needed to allow deploy single lambdas - otherwise error: needing artifacts
    handler: src/randomise.random # Path to lambda function
    events: # Define how the lambda will be invoked
      - http:
          method: POST
          path: randomise
          cors: true
  secretsanta:
    package: {}
    handler: src/api/email.send
    events:
      - http:
          method: POST
          path: send
          cors: true

# AWS Resources
resources:
  Resources:
    secretSantaRecords:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SecretSantaRecords
        KeySchema:
          - AttributeName: UUID
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: UUID
            AttributeType: S
          - AttributeName: Participant
            AttributeType: S
          - AttributeName: Party
            AttributeType: S
          - AttributeName: Email
            AttributeType: S
        GlobalSecondaryIndexes:
          - IndexName: ParticipantRecords
            KeySchema:
              - AttributeName: Participant
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes: ["Party"]
          - IndexName: PartyRecords
            KeySchema:
              - AttributeName: Party
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes: ["Participant"]
          - IndexName: EmailRecords
            KeySchema:
              - AttributeName: Email
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes: ["UUID"]
        BillingMode: PAY_PER_REQUEST
